apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: temporal-db

resources:
  - namespace.yaml
  - db-cluster.yaml

secretGenerator:
  - name: temporal-db-secret
    envs:
      - mysql.env

configurations:
  - nameReference.yaml
