apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: localstack

resources:
  # - namespace.yaml
  - base

images:
  - name: localstack
    newName: localstack/localstack
    newTag: "4.12.0"
