apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localstack
spec:
  rules:
    - host: localhost.localstack.cloud
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: localstack
                port:
                  number: 4566
