apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - pvc.yaml
  - service.yaml
  - ingress.yaml

configurations:
  - configuration.yaml

configMapGenerator:
  - name: init-localstack
    files:
      - files/init-scripts.sh
  - name: env-localstack
    envs:
      - files/localstack.env
